services:
  - type: web
    name: finglish-fixer-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    env: python
    plan: starter
    region: frankfurt
